In [4]:
import pandas as pd, numpy as np, statsmodels.api as sm

In [5]:
data = np.array([[24, 1355], [35, 603], [21, 192], [30, 224]])

In [6]:
data = np.append(data, (data[:,0]/(data[:,0] + data[:,1])).reshape(-1, 1), axis=1)

In [7]:
data

array([[  2.40000000e+01,   1.35500000e+03,   1.74039159e-02],
       [  3.50000000e+01,   6.03000000e+02,   5.48589342e-02],
       [  2.10000000e+01,   1.92000000e+02,   9.85915493e-02],
       [  3.00000000e+01,   2.24000000e+02,   1.18110236e-01]])

In [8]:
index = [0, 2, 4, 5]

In [9]:
df = pd.DataFrame(data = data, index = index, columns=['HD', 'No HD', 'HD Proportion'])

In [10]:
df

HD   No HD  HD Proportion
0  24.0  1355.0       0.017404
2  35.0   603.0       0.054859
4  21.0   192.0       0.098592
5  30.0   224.0       0.118110

In [11]:
X = sm.add_constant(df.index.values) # adds an intercept to the independent data

In [12]:
y = df['HD Proportion']

In [25]:
# The text example (identity link with Binomial) is not a supported linke in statsmodel. Binomial uses
# logit as the connonical link funct and probit and loglog are also supported.
results = sm.GLM(y, X, family=sm.families.Binomial(sm.families.links.identity)).fit() 

/usr/local/lib/python3.5/dist-packages/statsmodels/genmod/generalized_linear_model.py:244: DomainWarning: The identity link function does not respect the domain of the Binomial family.
  DomainWarning)


In [26]:
{'intercept': results.params.const, 'slope': results.params.x1}

{'intercept': 0.017015572026018291, 'slope': 0.020089533462987034}

In [27]:
results.predict(X) # results match textbook...mostly

array([ 0.01701557,  0.05719464,  0.09737371,  0.11746324])

In [28]:
# redo textbook example using the default Gaussian error function and identity link
results = sm.GLM(y, X,).fit() 

In [29]:
{'intercept': results.params.const, 'slope': results.params.x1}

{'intercept': 0.016312218434453643, 'slope': 0.020337796529889533}

In [30]:
results.predict(X)

array([ 0.01631222,  0.05698781,  0.0976634 ,  0.1180012 ])

In [32]:
X = sm.add_constant([0, 2, 4, 6])

In [44]:
results = sm.GLM(y, X, family=sm.families.Binomial(sm.families.links.identity)).fit() 

/usr/local/lib/python3.5/dist-packages/statsmodels/genmod/generalized_linear_model.py:244: DomainWarning: The identity link function does not respect the domain of the Binomial family.
  DomainWarning)


In [45]:
{'intercept': results.params.const, 'slope': results.params.x1}

{'intercept': -0.017818427977993018, 'slope': 0.035993722511577071}

In [46]:
results.predict(X)

array([ 0.01817529,  0.05416902,  0.09016274,  0.12615646])

In [47]:
X = sm.add_constant([0, 1, 2, 3])

In [48]:
results = sm.GLM(y, X, family=sm.families.Binomial(sm.families.links.identity)).fit() 

/usr/local/lib/python3.5/dist-packages/statsmodels/genmod/generalized_linear_model.py:244: DomainWarning: The identity link function does not respect the domain of the Binomial family.
  DomainWarning)


In [49]:
{'intercept': results.params.const, 'slope': results.params.x1}

{'intercept': 0.018175294533584054, 'slope': 0.035993722511577071}

In [50]:
results.predict(X)

array([ 0.01817529,  0.05416902,  0.09016274,  0.12615646])

In [51]:
X = sm.add_constant([1, 2, 3, 4])

In [52]:
results = sm.GLM(y, X, family=sm.families.Binomial(sm.families.links.identity)).fit() 

/usr/local/lib/python3.5/dist-packages/statsmodels/genmod/generalized_linear_model.py:244: DomainWarning: The identity link function does not respect the domain of the Binomial family.
  DomainWarning)


In [53]:
{'intercept': results.params.const, 'slope': results.params.x1}

{'intercept': -0.017818427977993018, 'slope': 0.035993722511577071}

In [54]:
results.predict(X)

array([ 0.01817529,  0.05416902,  0.09016274,  0.12615646])